version: "3"
services:
  eclipse:
    image: irt/eclipse:mars
    build:
      context: .
      dockerfile: eclipse-mars-oracle-jdk7.dockerfile
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${HOME}/workspace:/root/workspace"
      - "${HOME}/.eclipse:/root/.eclipse"
    networks: ["db"]

  sgbdmysql:
    image: mysql
    ports: ["3306:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: a24h
      MYSQL_DATABASE: a24h
      MYSQL_USER: a24h
      MYSQL_PASSWORD: a24h
    volumes:
      - "dados:/var/lib/mysql"
    networks: ["db"]

volumes:
  dados:

networks:
  db:

