version: "3"
services:
  eclipse:
    image: irt/eclipse:oxygen
    build:
      context: .
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${HOME}/.eclipse-docker:/home/developer"
      - "${HOME}:/workspace"
